name: docker build
on:
  push:
    branches:
      - master

jobs:
  mono-runtime:
    runs-on: ubuntu-latest
    steps:
      - name: clone
        uses: actions/checkout@master
      - name: build
        uses: triptixx/action-docker-build@master
        with:
          repo: mono-runtime-dev
      - name: test
        uses: triptixx/action-docker-test@master
        with:
          verbose: true
          repo: mono-runtime-dev
          run: su-exec nobody mono --version
      - name: publish
        uses: triptixx/action-docker-publish@master
        with:
          docker_username: ${{ secrets.docker_username }}
          docker_password: ${{ secrets.docker_password }}
          from: mono-runtime-dev
          repo: ${{ secrets.docker_username }}/mono-runtime
          tags: latest,%label org.label-schema.version | %auto
